const countrys = [
  {
    id: 1,
    code: "AED",
    country: "United Arab Emirates",
    currency: "UAE Dirham",
    flag: "🇦🇪",
  },
  {
    id: 2,
    code: "AFN",
    country: "Afghanistan",
    currency: "Afghan Afghani",
    flag: "🇦🇫",
  },
  {
    id: 3,
    code: "ALL",
    country: "Albania",
    currency: "Albanian Lek",
    flag: "🇦🇱",
  },
  {
    id: 4,
    code: "AMD",
    country: "Armenia",
    currency: "Armenian Dram",
    flag: "🇦🇲",
  },
  {
    id: 5,
    code: "ANG",
    country: "Netherlands Antilles",
    currency: "Netherlands Antillian Guilder",
    flag: "🇳🇱",
  },
  {
    id: 6,
    code: "AOA",
    country: "Angola",
    currency: "Angolan Kwanza",
    flag: "🇦🇴",
  },
  {
    id: 7,
    code: "ARS",
    country: "Argentina",
    currency: "Argentine Peso",
    flag: "🇦🇷",
  },
  {
    id: 8,
    code: "AUD",
    country: "Australia",
    currency: "Australian Dollar",
    flag: "🇦🇺",
  },
  {
    id: 9,
    code: "AWG",
    country: "Aruba",
    currency: "Aruban Florin",
    flag: "🇦🇼",
  },
  {
    id: 10,
    code: "AZN",
    country: "Azerbaijan",
    currency: "Azerbaijani Manat",
    flag: "🇦🇿",
  },
  {
    id: 11,
    code: "BAM",
    country: "Bosnia and Herzegovina",
    currency: "Bosnia and Herzegovina Mark",
    flag: "🇧🇦",
  },
  {
    id: 12,
    code: "BBD",
    country: "Barbados",
    currency: "Barbados Dollar",
    flag: "🇧🇧",
  },
  {
    id: 13,
    code: "BDT",
    country: "Bangladesh",
    currency: "Bangladeshi Taka",
    flag: "🇧🇩",
  },
  {
    id: 14,
    code: "BGN",
    country: "Bulgaria",
    currency: "Bulgarian Lev",
    flag: "🇧🇬",
  },
  {
    id: 15,
    code: "BHD",
    country: "Bahrain",
    currency: "Bahraini Dinar",
    flag: "🇧🇭",
  },
  {
    id: 16,
    code: "BIF",
    country: "Burundi",
    currency: "Burundian Franc",
    flag: "🇧🇮",
  },
  {
    id: 17,
    code: "BMD",
    country: "Bermuda",
    currency: "Bermudian Dollar",
    flag: "🇧🇲",
  },
  {
    id: 18,
    code: "BND",
    country: "Brunei",
    currency: "Brunei Dollar",
    flag: "🇧🇳",
  },
  {
    id: 19,
    code: "BOB",
    country: "Bolivia",
    currency: "Bolivian Boliviano",
    flag: "🇧🇴",
  },
  {
    id: 20,
    code: "BRL",
    country: "Brazil",
    currency: "Brazilian Real",
    flag: "🇧🇷",
  },
  {
    id: 21,
    code: "BSD",
    country: "Bahamas",
    currency: "Bahamian Dollar",
    flag: "🇧🇸",
  },
  {
    id: 22,
    code: "BTN",
    country: "Bhutan",
    currency: "Bhutanese Ngultrum",
    flag: "🇧🇹",
  },
  {
    id: 23,
    code: "BWP",
    country: "Botswana",
    currency: "Botswana Pula",
    flag: "🇧🇼",
  },
  {
    id: 24,
    code: "BYN",
    country: "Belarus",
    currency: "Belarusian Ruble",
    flag: "🇧🇾",
  },
  {
    id: 25,
    code: "BZD",
    country: "Belize",
    currency: "Belize Dollar",
    flag: "🇧🇿",
  },
  {
    id: 26,
    code: "CAD",
    country: "Canada",
    currency: "Canadian Dollar",
    flag: "🇨🇦",
  },
  {
    id: 27,
    code: "CDF",
    country: "Democratic Republic of the Congo",
    currency: "Congolese Franc",
    flag: "🇨🇩",
  },
  {
    id: 28,
    code: "CHF",
    country: "Switzerland",
    currency: "Swiss Franc",
    flag: "🇨🇭",
  },
  {
    id: 29,
    code: "CLP",
    country: "Chile",
    currency: "Chilean Peso",
    flag: "🇨🇱",
  },
  {
    id: 30,
    code: "CNY",
    country: "China",
    currency: "Chinese Renminbi",
    flag: "🇨🇳",
  },
  {
    id: 31,
    code: "COP",
    country: "Colombia",
    currency: "Colombian Peso",
    flag: "🇨🇴",
  },
  {
    id: 32,
    code: "CRC",
    country: "Costa Rica",
    currency: "Costa Rican Colon",
    flag: "🇨🇷",
  },
  { id: 33, code: "CUP", country: "Cuba", currency: "Cuban Peso", flag: "🇨🇺" },
  {
    id: 34,
    code: "CVE",
    country: "Cape Verde",
    currency: "Cape Verdean Escudo",
    flag: "🇨🇻",
  },
  {
    id: 35,
    code: "CZK",
    country: "Czech Republic",
    currency: "Czech Koruna",
    flag: "🇨🇿",
  },
  {
    id: 36,
    code: "DJF",
    country: "Djibouti",
    currency: "Djiboutian Franc",
    flag: "🇩🇯",
  },
  {
    id: 37,
    code: "DKK",
    country: "Denmark",
    currency: "Danish Krone",
    flag: "🇩🇰",
  },
  {
    id: 38,
    code: "DOP",
    country: "Dominican Republic",
    currency: "Dominican Peso",
    flag: "🇩🇴",
  },
  {
    id: 39,
    code: "DZD",
    country: "Algeria",
    currency: "Algerian Dinar",
    flag: "🇩🇿",
  },
  {
    id: 40,
    code: "EGP",
    country: "Egypt",
    currency: "Egyptian Pound",
    flag: "🇪🇬",
  },
  {
    id: 41,
    code: "ERN",
    country: "Eritrea",
    currency: "Eritrean Nakfa",
    flag: "🇪🇷",
  },
  {
    id: 42,
    code: "ETB",
    country: "Ethiopia",
    currency: "Ethiopian Birr",
    flag: "🇪🇹",
  },
  {
    id: 43,
    code: "EUR",
    country: "European Union",
    currency: "Euro",
    flag: "🇪🇺",
  },
  { id: 44, code: "FJD", country: "Fiji", currency: "Fiji Dollar", flag: "🇫🇯" },
  {
    id: 45,
    code: "FKP",
    country: "Falkland Islands",
    currency: "Falkland Islands Pound",
    flag: "🇫🇰",
  },
  {
    id: 46,
    code: "FOK",
    country: "Faroe Islands",
    currency: "Faroese Króna",
    flag: "🇫🇴",
  },
  {
    id: 47,
    code: "GBP",
    country: "United Kingdom",
    currency: "Pound Sterling",
    flag: "🇬🇧",
  },
  {
    id: 48,
    code: "GEL",
    country: "Georgia",
    currency: "Georgian Lari",
    flag: "🇬🇪",
  },
  {
    id: 49,
    code: "GGP",
    country: "Guernsey",
    currency: "Guernsey Pound",
    flag: "🇬🇬",
  },
  {
    id: 50,
    code: "GHS",
    country: "Ghana",
    currency: "Ghanaian Cedi",
    flag: "🇬🇭",
  },
  {
    id: 51,
    code: "GIP",
    country: "Gibraltar",
    currency: "Gibraltar Pound",
    flag: "🇬🇮",
  },
  {
    id: 52,
    code: "GMD",
    country: "The Gambia",
    currency: "Gambian Dalasi",
    flag: "🇬🇲",
  },
  {
    id: 53,
    code: "GNF",
    country: "Guinea",
    currency: "Guinean Franc",
    flag: "🇬🇳",
  },
  {
    id: 54,
    code: "GTQ",
    country: "Guatemala",
    currency: "Guatemalan Quetzal",
    flag: "🇬🇹",
  },
  {
    id: 55,
    code: "GYD",
    country: "Guyana",
    currency: "Guyanese Dollar",
    flag: "🇬🇾",
  },
  {
    id: 56,
    code: "HKD",
    country: "Hong Kong",
    currency: "Hong Kong Dollar",
    flag: "🇭🇰",
  },
  {
    id: 57,
    code: "HNL",
    country: "Honduras",
    currency: "Honduran Lempira",
    flag: "🇭🇳",
  },
  {
    id: 58,
    code: "HRK",
    country: "Croatia",
    currency: "Croatian Kuna",
    flag: "🇭🇷",
  },
  {
    id: 59,
    code: "HTG",
    country: "Haiti",
    currency: "Haitian Gourde",
    flag: "🇭🇹",
  },
  {
    id: 60,
    code: "HUF",
    country: "Hungary",
    currency: "Hungarian Forint",
    flag: "🇭🇺",
  },
  {
    id: 61,
    code: "IDR",
    country: "Indonesia",
    currency: "Indonesian Rupiah",
    flag: "🇮🇩",
  },
  {
    id: 62,
    code: "ILS",
    country: "Israel",
    currency: "Israeli New Shekel",
    flag: "🇮🇱",
  },
  {
    id: 63,
    code: "IMP",
    country: "Isle of Man",
    currency: "Manx Pound",
    flag: "🇮🇲",
  },
  {
    id: 64,
    code: "INR",
    country: "India",
    currency: "Indian Rupee",
    flag: "🇮🇳",
  },
  { id: 65, code: "IQD", country: "Iraq", currency: "Iraqi Dinar", flag: "🇮🇶" },
  {
    id: 66,
    code: "IRR",
    country: "Iran",
    currency: "Iranian Rial",
    flag: "🇮🇷",
  },
  {
    id: 67,
    code: "ISK",
    country: "Iceland",
    currency: "Icelandic Króna",
    flag: "🇮🇸",
  },
  {
    id: 68,
    code: "JEP",
    country: "Jersey",
    currency: "Jersey Pound",
    flag: "🇯🇪",
  },
  {
    id: 69,
    code: "JMD",
    country: "Jamaica",
    currency: "Jamaican Dollar",
    flag: "🇯🇲",
  },
  {
    id: 70,
    code: "JOD",
    country: "Jordan",
    currency: "Jordanian Dinar",
    flag: "🇯🇴",
  },
  {
    id: 71,
    code: "JPY",
    country: "Japan",
    currency: "Japanese Yen",
    flag: "🇯🇵",
  },
  {
    id: 72,
    code: "KES",
    country: "Kenya",
    currency: "Kenyan Shilling",
    flag: "🇰🇪",
  },
  {
    id: 73,
    code: "KGS",
    country: "Kyrgyzstan",
    currency: "Kyrgyzstani Som",
    flag: "🇰🇬",
  },
  {
    id: 74,
    code: "KHR",
    country: "Cambodia",
    currency: "Cambodian Riel",
    flag: "🇰🇭",
  },
  {
    id: 75,
    code: "KID",
    country: "Kiribati",
    currency: "Kiribati Dollar",
    flag: "🇰🇮",
  },
  {
    id: 76,
    code: "KMF",
    country: "Comoros",
    currency: "Comorian Franc",
    flag: "🇰🇲",
  },
  {
    id: 77,
    code: "KRW",
    country: "South Korea",
    currency: "South Korean Won",
    flag: "🇰🇷",
  },
  {
    id: 78,
    code: "KWD",
    country: "Kuwait",
    currency: "Kuwaiti Dinar",
    flag: "🇰🇼",
  },
  {
    id: 79,
    code: "KYD",
    country: "Cayman Islands",
    currency: "Cayman Islands Dollar",
    flag: "🇰🇾",
  },
  {
    id: 80,
    code: "KZT",
    country: "Kazakhstan",
    currency: "Kazakhstani Tenge",
    flag: "🇰🇿",
  },
  { id: 81, code: "LAK", country: "Laos", currency: "Lao Kip", flag: "🇱🇦" },
  {
    id: 82,
    code: "LBP",
    country: "Lebanon",
    currency: "Lebanese Pound",
    flag: "🇱🇧",
  },
  {
    id: 83,
    code: "LKR",
    country: "Sri Lanka",
    currency: "Sri Lanka Rupee",
    flag: "🇱🇰",
  },
  {
    id: 84,
    code: "LRD",
    country: "Liberia",
    currency: "Liberian Dollar",
    flag: "🇱🇷",
  },
  {
    id: 85,
    code: "LSL",
    country: "Lesotho",
    currency: "Lesotho Loti",
    flag: "🇱🇸",
  },
  {
    id: 86,
    code: "LYD",
    country: "Libya",
    currency: "Libyan Dinar",
    flag: "🇱🇾",
  },
  {
    id: 87,
    code: "MAD",
    country: "Morocco",
    currency: "Moroccan Dirham",
    flag: "🇲🇦",
  },
  {
    id: 88,
    code: "MDL",
    country: "Moldova",
    currency: "Moldovan Leu",
    flag: "🇲🇩",
  },
  {
    id: 89,
    code: "MGA",
    country: "Madagascar",
    currency: "Malagasy Ariary",
    flag: "🇲🇬",
  },
  {
    id: 90,
    code: "MKD",
    country: "North Macedonia",
    currency: "Macedonian Denar",
    flag: "🇲🇰",
  },
  {
    id: 91,
    code: "MMK",
    country: "Myanmar",
    currency: "Burmese Kyat",
    flag: "🇲🇲",
  },
  {
    id: 92,
    code: "MNT",
    country: "Mongolia",
    currency: "Mongolian Tögrög",
    flag: "🇲🇳",
  },
  {
    id: 93,
    code: "MOP",
    country: "Macau",
    currency: "Macanese Pataca",
    flag: "🇲🇴",
  },
  {
    id: 94,
    code: "MRU",
    country: "Mauritania",
    currency: "Mauritanian Ouguiya",
    flag: "🇲🇷",
  },
  {
    id: 95,
    code: "MUR",
    country: "Mauritius",
    currency: "Mauritian Rupee",
    flag: "🇲🇺",
  },
  {
    id: 96,
    code: "MVR",
    country: "Maldives",
    currency: "Maldivian Rufiyaa",
    flag: "🇲🇻",
  },
  {
    id: 97,
    code: "MWK",
    country: "Malawi",
    currency: "Malawian Kwacha",
    flag: "🇲🇼",
  },
  {
    id: 98,
    code: "MXN",
    country: "Mexico",
    currency: "Mexican Peso",
    flag: "🇲🇽",
  },
  {
    id: 99,
    code: "MYR",
    country: "Malaysia",
    currency: "Malaysian Ringgit",
    flag: "🇲🇾",
  },
  {
    id: 100,
    code: "MZN",
    country: "Mozambique",
    currency: "Mozambican Metical",
    flag: "🇲🇿",
  },
  {
    id: 101,
    code: "NAD",
    country: "Namibia",
    currency: "Namibian Dollar",
    flag: "🇳🇦",
  },
  {
    id: 102,
    code: "NGN",
    country: "Nigeria",
    currency: "Nigerian Naira",
    flag: "🇳🇬",
  },
  {
    id: 103,
    code: "NIO",
    country: "Nicaragua",
    currency: "Nicaraguan Córdoba",
    flag: "🇳🇮",
  },
  {
    id: 104,
    code: "NOK",
    country: "Norway",
    currency: "Norwegian Krone",
    flag: "🇳🇴",
  },
  {
    id: 105,
    code: "NPR",
    country: "Nepal",
    currency: "Nepalese Rupee",
    flag: "🇳🇵",
  },
  {
    id: 106,
    code: "NZD",
    country: "New Zealand",
    currency: "New Zealand Dollar",
    flag: "🇳🇿",
  },
  { id: 107, code: "OMR", country: "Oman", currency: "Omani Rial", flag: "🇴🇲" },
  {
    id: 108,
    code: "PAB",
    country: "Panama",
    currency: "Panamanian Balboa",
    flag: "🇵🇦",
  },
  {
    id: 109,
    code: "PEN",
    country: "Peru",
    currency: "Peruvian Sol",
    flag: "🇵🇪",
  },
  {
    id: 110,
    code: "PGK",
    country: "Papua New Guinea",
    currency: "Papua New Guinean Kina",
    flag: "🇵🇬",
  },
  {
    id: 111,
    code: "PHP",
    country: "Philippines",
    currency: "Philippine Peso",
    flag: "🇵🇭",
  },
  {
    id: 112,
    code: "PKR",
    country: "Pakistan",
    currency: "Pakistani Rupee",
    flag: "🇵🇰",
  },
  {
    id: 113,
    code: "PLN",
    country: "Poland",
    currency: "Polish Złoty",
    flag: "🇵🇱",
  },
  {
    id: 114,
    code: "PYG",
    country: "Paraguay",
    currency: "Paraguayan Guaraní",
    flag: "🇵🇾",
  },
  {
    id: 115,
    code: "QAR",
    country: "Qatar",
    currency: "Qatari Riyal",
    flag: "🇶🇦",
  },
  {
    id: 116,
    code: "RON",
    country: "Romania",
    currency: "Romanian Leu",
    flag: "🇷🇴",
  },
  {
    id: 117,
    code: "RSD",
    country: "Serbia",
    currency: "Serbian Dinar",
    flag: "🇷🇸",
  },
  {
    id: 118,
    code: "RUB",
    country: "Russia",
    currency: "Russian Ruble",
    flag: "🇷🇺",
  },
  {
    id: 119,
    code: "RWF",
    country: "Rwanda",
    currency: "Rwandan Franc",
    flag: "🇷🇼",
  },
  {
    id: 120,
    code: "SAR",
    country: "Saudi Arabia",
    currency: "Saudi Riyal",
    flag: "🇸🇦",
  },
  {
    id: 121,
    code: "SBD",
    country: "Solomon Islands",
    currency: "Solomon Islands Dollar",
    flag: "🇸🇧",
  },
  {
    id: 122,
    code: "SCR",
    country: "Seychelles",
    currency: "Seychellois Rupee",
    flag: "🇸🇨",
  },
  {
    id: 123,
    code: "SDG",
    country: "Sudan",
    currency: "Sudanese Pound",
    flag: "🇸🇩",
  },
  {
    id: 124,
    code: "SEK",
    country: "Sweden",
    currency: "Swedish Krona",
    flag: "🇸🇪",
  },
  {
    id: 125,
    code: "SGD",
    country: "Singapore",
    currency: "Singapore Dollar",
    flag: "🇸🇬",
  },
  {
    id: 126,
    code: "SHP",
    country: "Saint Helena",
    currency: "Saint Helena Pound",
    flag: "🇸🇭",
  },
  {
    id: 127,
    code: "SLE",
    country: "Sierra Leone",
    currency: "Sierra Leonean Leone",
    flag: "🇸🇱",
  },
  {
    id: 128,
    code: "SOS",
    country: "Somalia",
    currency: "Somali Shilling",
    flag: "🇸🇴",
  },
  {
    id: 129,
    code: "SRD",
    country: "Suriname",
    currency: "Surinamese Dollar",
    flag: "🇸🇷",
  },
  {
    id: 130,
    code: "SSP",
    country: "South Sudan",
    currency: "South Sudanese Pound",
    flag: "🇸🇸",
  },
  {
    id: 131,
    code: "STN",
    country: "São Tomé and Príncipe",
    currency: "São Tomé and Príncipe Dobra",
    flag: "🇸🇹",
  },
  {
    id: 132,
    code: "SYP",
    country: "Syria",
    currency: "Syrian Pound",
    flag: "🇸🇾",
  },
  {
    id: 133,
    code: "SZL",
    country: "Eswatini",
    currency: "Eswatini Lilangeni",
    flag: "🇸🇿",
  },
  {
    id: 134,
    code: "THB",
    country: "Thailand",
    currency: "Thai Baht",
    flag: "🇹🇭",
  },
  {
    id: 135,
    code: "TJS",
    country: "Tajikistan",
    currency: "Tajikistani Somoni",
    flag: "🇹🇯",
  },
  {
    id: 136,
    code: "TMT",
    country: "Turkmenistan",
    currency: "Turkmenistan Manat",
    flag: "🇹🇲",
  },
  {
    id: 137,
    code: "TND",
    country: "Tunisia",
    currency: "Tunisian Dinar",
    flag: "🇹🇳",
  },
  {
    id: 138,
    code: "TOP",
    country: "Tonga",
    currency: "Tongan Paʻanga",
    flag: "🇹🇴",
  },
  {
    id: 139,
    code: "TRY",
    country: "Turkey",
    currency: "Turkish Lira",
    flag: "🇹🇷",
  },
  {
    id: 140,
    code: "TTD",
    country: "Trinidad and Tobago",
    currency: "Trinidad and Tobago Dollar",
    flag: "🇹🇹",
  },
  {
    id: 141,
    code: "TVD",
    country: "Tuvalu",
    currency: "Tuvaluan Dollar",
    flag: "🇹🇻",
  },
  {
    id: 142,
    code: "TWD",
    country: "Taiwan",
    currency: "New Taiwan Dollar",
    flag: "🇹🇼",
  },
  {
    id: 143,
    code: "TZS",
    country: "Tanzania",
    currency: "Tanzanian Shilling",
    flag: "🇹🇿",
  },
  {
    id: 144,
    code: "UAH",
    country: "Ukraine",
    currency: "Ukrainian Hryvnia",
    flag: "🇺🇦",
  },
  {
    id: 145,
    code: "UGX",
    country: "Uganda",
    currency: "Ugandan Shilling",
    flag: "🇺🇬",
  },
  {
    id: 146,
    code: "USD",
    country: "United States",
    currency: "United States Dollar",
    flag: "🇺🇸",
  },
  {
    id: 147,
    code: "UYU",
    country: "Uruguay",
    currency: "Uruguayan Peso",
    flag: "🇺🇾",
  },
  {
    id: 148,
    code: "UZS",
    country: "Uzbekistan",
    currency: "Uzbekistani So'm",
    flag: "🇺🇿",
  },
  {
    id: 149,
    code: "VES",
    country: "Venezuela",
    currency: "Venezuelan Bolívar Soberano",
    flag: "🇻🇪",
  },
  {
    id: 150,
    code: "VND",
    country: "Vietnam",
    currency: "Vietnamese Đồng",
    flag: "🇻🇳",
  },
  {
    id: 151,
    code: "VUV",
    country: "Vanuatu",
    currency: "Vanuatu Vatu",
    flag: "🇻🇺",
  },
  {
    id: 152,
    code: "WST",
    country: "Samoa",
    currency: "Samoan Tālā",
    flag: "🇼🇸",
  },
  {
    id: 153,
    code: "XAF",
    country: "CEMAC",
    currency: "Central African CFA Franc",
    flag: "🇨🇲",
  },
  {
    id: 154,
    code: "XCD",
    country: "Organisation of Eastern Caribbean States",
    currency: "East Caribbean Dollar",
    flag: "🇪🇨",
  },
  {
    id: 155,
    code: "XDR",
    country: "International Monetary Fund",
    currency: "Special Drawing Rights",
    flag: "🇮🇲",
  },
  {
    id: 156,
    code: "XOF",
    country: "CFA",
    currency: "West African CFA franc",
    flag: "🇳🇪",
  },
  {
    id: 157,
    code: "XPF",
    country: "Collectivités d'Outre-Mer",
    currency: "CFP Franc",
    flag: "🇵🇫",
  },
  {
    id: 158,
    code: "YER",
    country: "Yemen",
    currency: "Yemeni Rial",
    flag: "🇾🇪",
  },
  {
    id: 159,
    code: "ZAR",
    country: "South Africa",
    currency: "South African Rand",
    flag: "🇿🇦",
  },
  {
    id: 160,
    code: "ZMW",
    country: "Zambia",
    currency: "Zambian Kwacha",
    flag: "🇿🇲",
  },
  {
    id: 161,
    code: "ZWL",
    country: "Zimbabwe",
    currency: "Zimbabwean Dollar",
    flag: "🇿🇼",
  },
];
